
# Pedir data al servidor
GET http://localhost:5000/calculo HTTP/1.1

###

POST http://localhost:5000/calculo HTTP/1.1
content-type: application/json

{
    "numeroA": 15,
    "numeroB": 16,
    "user": "administrator"
}

###



POST http://localhost:5000/parques HTTP/1.1
content-type: application/json

{
    "parque_nacional" : {
        "province": "Salta",
        "name": "Nahuel Papi",
        "region": "Región NOA"
    }
}
